# Generated by Django 4.0.3 on 2022-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='position',
        ),
        migrations.AddField(
            model_name='sale',
            name='positions',
            field=models.ManyToManyField(to='sales.position'),
        ),
    ]
